# Basic
title: Jianstm
subtitle: Share My Thoughts
welcome_message: <a href="https://ioscaff.com/" target="_blank">iOSCaff</a> 是一个新成立的 iOS 开发者社区，欢迎大家加入！
description: 嗨，我是 Jianstm，现居深圳。我会在这里写些东西，分享我的想法。
creator: <a href="http://onev.cat">@Jianstm</a>

url: "http://v2ambition.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About, description: About, url: '/aboutme'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: v2ambition
    # duoshuo: 
    
# Social
social:
    github: jianstm
    weibo: jianstm
    mail: jianstm@gmail.com

# Google Analytics
ga:
    id: UA-113585198-1
    host: v2ambition.com
