# Basic
title: wbq
subtitle: 汪炳权个人博客
welcome_message: 先完成，再完美。
#description: 嗨，我是 wbq，现居宁波。我会在这里写些东西，分享我的想法。\n
creator: <a href="https://github.com/Wbqqqq">@wbq</a>

url: "http://v2ambition.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About, description: About, url: '/aboutme'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus:
    # duoshuo: 
    
# Social
social:
    github: Wbqqqq
    weibo:
    mail: 353351363@qq.com

# Google Analytics
ga:
    id:
    host:
